### ISSUE TITLE
How to retreive historical global/aggregated market cap data?

### ISSUE THREAD

**Issue by adragosch** [sstoeckl/crypto2#10]
Hi there,

I would like to retreive the historical global/aggregated marketcap over all coins as shown in the first chart here: https://coinmarketcap.com/charts/

Unfortunately, I haven't found the respective function in the package reference.

Any help would be highly appreciated!

Thank you very much in advance for a short reply.

Best,
André

**Comment by sstoeckl** [comment]
Hi @adragosch  I have now checked and think I will make the global metrics available. I would appreciate support!

**Comment by adragosch** [comment]
Hi Sebastian, Thanks for your reply. I am not a pro in HTML unfortunately and not so familiar w/ rvest either. If I was, I would definitely help you.

**Comment by sstoeckl** [comment]
Hi @adragosch I have just uploaded a new version of the package to github (1.4.5) with a new function `crypto_global_quotes()` which is designed to do what you want without having to download all individual coins. Also, check the readme file. Once you confirm I will submit the package to cran.

**Comment by adragosch** [comment]
Hi Sebastian, Thank you so much! I have checked the newest version and apparently I can only retreive the latest values from CMC but not a time series. 

Even if I type in the following code I only get the latest values in a 1 x 23 tibble:

crypto_global_quotes(start_date="20220101", end_date="20221010", interval="daily")

identical output for the following call:
crypto_global_quotes(which="latest")

Am I doing sth wrong?

Thanks ain advance for a short reply.

**Comment by sstoeckl** [comment]
Hi @adragosch : You are using the command wrong. If you want historical data you have to specify _which=historical_: `crypto_global_quotes(which = "historical", start_date="20220101", end_date="20221010", interval="daily")`
