### ISSUE TITLE
Is it still free to get the historical data? 

### ISSUE THREAD

**Issue by smolendawid** [sstoeckl/crypto2#11]
I can see in the documentation that

https://coinmarketcap.com/api/documentation/v1/#operation/getV1CryptocurrencyListingsHistorical

This endpoint is available on the following [API plans](https://coinmarketcap.com/api/features) - the cheapest plans don't allow to use this endpoint.

I'm not R developer, what I'd like to get are the prices of top N market-cap cryptos over a few years by day.

Can I expect crypto2 to allow me to get this data?

**Comment by sstoeckl** [comment]
Yes. Exactly as it is stated in the documentation.

**Comment by sstoeckl** [comment]
Closed

**Comment by smolendawid** [comment]
@sstoeckl excuse me, but the documentations says the endpoint `/v1/cryptocurrency/listings/historical` is not free. 
Is it possible to fetch historical data then using crypto2?

**Comment by sstoeckl** [comment]
@smolendawid Why do you not just try it? I have taken the liberty to update the code and allow to new variables: "sort" to tell `crypto_listings()` in combination with "limit" which variable to use for sorting the returned data (and therefore with results to return). This includes a variable "sort_dir". Example:
`crypto_listings(which="historical", quote=TRUE,start_date = "20150101", end_date="20150107", interval="day", sort="market_cap", sort_dir="desc", limit=10)`
For this to run you have to install the development version from github.

**Comment by smolendawid** [comment]
Thanks for the answer. I'm not R developer, I did not want to set up the whole environment, IDE etc, without knowing I can really use crypto2 for my purpose.
