### ISSUE TITLE
crypto_list() error

### ISSUE THREAD

**Issue by chriscarrollsmith** [sstoeckl/crypto2#13]
This package has always worked for me before, but today I am getting this error when I use crypto_list():

Error: Problem with `mutate()` input `..1`.
i `..1 = dplyr::across(7:8, as.Date)`.
x 'origin' must be supplied

**Comment by sstoeckl** [comment]
Bad programming (non-named column reference). CMC added a new variable to the dataset and therefore the reference was wrong. Fixed in https://github.com/sstoeckl/crypto2/commit/d155ee0c1a1667a87d0a7a31a616a6339a1bd7d8.
