### ISSUE TITLE
Use data.frame over tibble 

### ISSUE THREAD

**Issue by waynelapierre** [sstoeckl/crypto2#16]
Thanks for this great package. Is there any reason for using tibble over data.frame as the data format? Tibble is as slow as data.frame but more noisey, and can cause issues when converted to data.table. Would you consider using data.frame as the data format?

**Comment by sstoeckl** [comment]
I am huge supporter of the tidyverse and therefore decided to go with tibbles. Feel free to provide a branch with data.frame access!
