### ISSUE TITLE
Is there a way to categorize coins by consensus mechanism?

### ISSUE THREAD

**Issue by adragosch** [sstoeckl/crypto2#17]
Hey there,

First of all, I just wanted to say that the package is really really good and I am a very happy user!

I was wondering whether there is a way to retrieve a list of coins (and time series) based on consensus mechanism such as "proof-of-work"?

For instance, there is a list of pow coins on CMC:
https://coinmarketcap.com/view/pow/

I have also found a category identifier in the API description on CMC called "consensus_mechanism" (see attachment).

That way crypto2 package users would be able to create coin indices based on consensus mechanism as well.

Thank you very much in advance for a short reply!

Best regards,
André

![image](https://user-images.githubusercontent.com/56151516/235933350-fd27063f-4545-48fc-8214-d87902460691.png)

**Comment by sstoeckl** [comment]
Hi André, there is a way to access this blockchain mechanism, however it does not allow for historical information and only provides current information that is updated every 15s. Without history I do not see any research purpose with this endpoint and therefore will not implement it (if there are volunteers please feel free to commit your suggestion!).

BUT: If you download information for each cc among the attribute `tag` it gives information on "pow", "pos" etc. I would try to filter the info of all coins accordingly (be aware this is only current information!) and build my index from there!

Keep me posted whether this works!

Best, Sebastian
