### ISSUE TITLE
Error in interval time smaller than daily

### ISSUE THREAD

**Issue by Mettez14** [sstoeckl/crypto2#19]
When trying to collect historical price data of e.g., BTC for time intervals smaller than daily, I run into errors.

For example:
CMC_coin_data <- crypto_history(selected_coin, finalWait=FALSE, interval="hourly")

will give this error:
In crypto_history(selected_coin, finalWait = FALSE, interval = "hourly") :
  interval was not valid, using "daily". see documentation for allowed values.
  
  However, these work just fine:
  CMC_coin_data <- crypto_history(selected_coin, finalWait=FALSE, interval="daily")
  CMC_coin_data <- crypto_history(selected_coin, finalWait=FALSE, interval="monthly")
  
Which is strange, especially since the documentation in the crypto_history.R file states the following:

#' @param interval string Interval with which to sample data, default 'daily'. Must be one of `"hourly" "daily" "weekly"
#' "monthly" "yearly" "1d" "2d" "3d" "7d" "14d" "15d" "30d" "60d" "90d" "365d"`

Or am I missing something here? Thank you!

**Comment by sstoeckl** [comment]
This has been solved in the newest version, see readme and help!
