### ISSUE TITLE
rate limiting by coinmarketcap without API key

### ISSUE THREAD

**Issue by petero1111** [sstoeckl/crypto2#4]
I could only get 100 requests out before it threw HTTP error 429 for the rest of the day.

**Comment by sstoeckl** [comment]
Hi @petero1111 I have rewritten the code - it now retrieves as many coins per api call as possible thereby limiting this problem. However, coinmarketcap has introduced a new "feature", where, within one minute after the first api call, it just sends the same json package back. So between the various (now bulkier) calls to the api we have to wait 60s.

Does this solve your problem?

**Comment by sstoeckl** [comment]
See version v1.4.0
