### ISSUE TITLE
Error in if (limit == 1) { : argument is of length zero

### ISSUE THREAD

**Issue by deaniceman** [sstoeckl/crypto2#9]
Hello

crypto_history() returns the above error in most cases. It is particularly frustrating when it happens after a very long download time, as nothing is saved due to the error. Is there a way around this? Thanks

`> data_1 <- crypto_history(start_date = "20130101", end_date = "20130201", sleep = 1)`
`> Scraping historical crypto data`

`| [32 / 32] [=====================================================] 100% in 00:32:00 ETA:  0s`
`Error in if (limit == 1) { : argument is of length zero`
`> data_1`
`Error: object 'data_1' not found`

**Comment by sstoeckl** [comment]
Hi @deaniceman . This is due to the fact (I believe) that there is no data available before 2013-04-29 (bitcoin). I will add a date check though.

**Comment by sstoeckl** [comment]
Implemented in 370b2bc52688477b53572126428b783077122b1d. Thanks
